In [1]:
import cv2
import numpy

In [34]:
img=cv2.imread('resources/sample1.jpg',1)

In [38]:
cv2.imshow('window',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [27]:
type(img)

numpy.ndarray

In [36]:
for rows in img:
    for row in rows:
        for i in range(3):
            row[i]-=row[i]%10

In [37]:
print(img)

[[[250 250 250]
  [250 250 250]
  [250 240 240]
  ...
  [250 250 250]
  [250 250 250]
  [250 250 250]]

 [[250 250 250]
  [250 250 250]
  [250 250 250]
  ...
  [250 250 250]
  [250 250 250]
  [250 250 250]]

 [[250 250 250]
  [250 250 250]
  [250 250 250]
  ...
  [250 250 250]
  [250 250 250]
  [250 250 250]]

 ...

 [[250 250 250]
  [250 250 250]
  [250 250 250]
  ...
  [250 250 250]
  [250 250 250]
  [250 250 250]]

 [[250 250 250]
  [250 240 250]
  [250 250 250]
  ...
  [250 250 250]
  [250 250 250]
  [250 250 250]]

 [[250 240 250]
  [250 250 250]
  [250 250 250]
  ...
  [250 250 250]
  [250 250 250]
  [250 250 250]]]


In [33]:
len(img),len(img[0]),len(img[0][0])

(313, 837, 3)

In [8]:
img.shape

(465, 660, 3)

In [43]:
img[0][0][0]=259

In [47]:
for i in 'baliz':
    print(i,ord(i))

b 98
a 97
l 108
i 105
z 122
