In [28]:
import cv2
from numpy import *
def click_event(event,x,y,flags,param):
    pixel=uint8([[[0,0,0]]])
    if event == cv2.EVENT_FLAG_LBUTTON:
        try:
            b,g,r=img[y,x]
            pixel=uint8([[[b,g,r]]])
            hsv=cv2.cvtColor(pixel,cv2.COLOR_BGR2HSV)
            print(hsv)
            text=str(hsv)
            font=cv2.FONT_HERSHEY_SIMPLEX
            cv2.putText(img,text,(x,y),font,.4,(255-int(b),255-int(g),255-int(r)),1)
            cv2.imshow('photo',img)
        except Exception as e:
            print(e)
        


img=cv2.imread(input('enter the image name '),1)
cv2.imshow('photo',img)
cv2.setMouseCallback('photo',click_event)
cv2.waitKey(0)
cv2.destroyAllWindows()

enter the image name bali.jpg
[[[120  91  95]]]
[[[111  86  59]]]
[[[ 0 37 41]]]
[[[177  57  40]]]
[[[ 25   7 214]]]
