In [8]:
from numpy import *
arr=array([1,2,3])
for i in arr:
    print(i)
print(arr.dtype)
print('bye')

1
2
3
int32
bye


In [18]:
from numpy import *
arr=linspace(1,2)
print(arr)

[1.         1.02040816 1.04081633 1.06122449 1.08163265 1.10204082
 1.12244898 1.14285714 1.16326531 1.18367347 1.20408163 1.2244898
 1.24489796 1.26530612 1.28571429 1.30612245 1.32653061 1.34693878
 1.36734694 1.3877551  1.40816327 1.42857143 1.44897959 1.46938776
 1.48979592 1.51020408 1.53061224 1.55102041 1.57142857 1.59183673
 1.6122449  1.63265306 1.65306122 1.67346939 1.69387755 1.71428571
 1.73469388 1.75510204 1.7755102  1.79591837 1.81632653 1.83673469
 1.85714286 1.87755102 1.89795918 1.91836735 1.93877551 1.95918367
 1.97959184 2.        ]


In [19]:
arr=arange(1,15,2)
print(arr)

[ 1  3  5  7  9 11 13]


In [21]:
arr=zeros(5,int)
print(arr)

[0 0 0 0 0]


In [23]:
arr=ones(5,int)
print(arr)

[1 1 1 1 1]
