In [12]:
from numpy import *
arr1=array([1,2,3,4,5])
arr2=arr1.view()
arr1[1]=6
print(id(arr1),arr1)
print(id(arr2),arr2)

2523573227392 [1 6 3 4 5]
2523573227072 [1 6 3 4 5]


In [22]:
arr=array([[1,2,3,4],[1,4,9,16],[1,8,27,64]])
arr3=arr.flatten()
arr4=arr3.reshape(2,2,3)
print(arr4)

[[[ 1  2  3]
  [ 4  1  4]]

 [[ 9 16  1]
  [ 8 27 64]]]


In [26]:
m=matrix('1 2 3 4 5;6 7 8 9 0')
print(m)

[[1 2 3 4 5]
 [6 7 8 9 0]]
